# Generated by Django 4.2.7 on 2023-12-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default=1, max_length=255, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default=1, max_length=255, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_color',
            field=models.CharField(choices=[('красный', 'Красный'), ('зеленый', 'Зеленый'), ('синий', 'Синий'), ('желтый', 'Желтый'), ('черный', 'Черный'), ('белый', 'Белый')], default=1, max_length=255, verbose_name='Любимый цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.CharField(default=1, max_length=255, verbose_name='Организация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(default=1, max_length=255, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
